### PR TITLE
fix: default share(data) to empty dictionary

### LINKED ISSUE #109: why "optional" in share(optional ShareData data)?
Given that the first thing we need to check is if `data` has some members, shouldn't the share() signature actually make `data` required? 

Alternatively, the method signature should default to the empty dictionary: 

```
[SecureContext] Promise<void> share(optional ShareData data = {});
```

However, I think we should just make `data` required.

### PR DESCRIPTION
**Pull request by marcoscaceres**
fixes #109

### CODE REVIEW

**Comment by marcoscaceres** [comment]
We probably don't need the note anymore because now it's clear from the IDL that at least `{}` is always present. Now the algorithm always makes sense :)

**Comment by marcoscaceres** [comment]
I can’t recall if the IDL changes are automatically picked up on WPT. Also, any idea if https://github.com/heycam/webidl/pull/750 is implemented in Blink yet... I’m guessing not, but we should probably track that.

**Comment by ewilligers** [comment]
> any idea if heycam/webidl#750 is implemented in Blink yet?

No.
```
boolean canShare(optional ShareData data = {});
Promise<void> share(optional ShareData data = {});
```
gives
```
navigator_share.idl(12) : error: Unexpected "{" after "=".
navigator_share.idl(15) : error: Unexpected "{" after "=".
```

**Comment by marcoscaceres** [comment]
WPT also hasn’t updated to the latest version of WebIDL2.js, which includes support for this. Should hopefully happen by end of the week. 

Do we have a Chrome bug we can track? Should we file one?

**Comment by ewilligers** [comment]
Chrome bug for dictionaries with no required members:
https://bugs.chromium.org/p/chromium/issues/detail?id=948139

**Pull request merged**
